### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/25-days-of-serverless#114]
Please provide the following information for your submission:

### What is your name? (First, Last)
Barbara Forbes
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/Ba4bes/25daysofserverless (with folders for the different days
### What Challenge is this for? (Challenge number between 1 and 25)
3. (Had previous pull requests for 1 and 2)
### (Optional) Anything else we should know? e.g., language used, location, blog post?
PowerShell in Function App. 
I have added Readme's with short motivations and resources to all folders :)

**Comment by nitya** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository. 
We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 
This issue is now resolved! 🎉
