### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by stuartleaver** [microsoft/25-days-of-serverless#115]
Please provide the following information for your submission:

### What is your name? (First, Last)

Stuart Leaver

### Where is your GitHub Repo ?(With your challenge solution)

https://github.com/stuartleaver/25-days-of-serverless/tree/master/03-webhooks

### What Challenge is this for? (Challenge number between 1 and 25)

3

### (Optional) Anything else we should know? e.g., language used, location, blog post?

The Azure SQL Database is a serverless one in the spirit of the challenge.

Oh, any bonus points for using cat images for testing!!!!

**Comment by nitya** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository. 
We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 
This issue is now resolved! 🎉
