### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by davidojedalopez** [microsoft/25-days-of-serverless#122]
Please provide the following information for your submission:

### What is your name? (First, Last)
David Ojeda

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/davidojedalopez/day-03

### What Challenge is this for? (Challenge number between 1 and 25)
3

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Used AWS SAM CLI with Node12 runtime. AWS services involved: Lambda, DynamoDB, API Gateway, CloudFormation

**Comment by glaucia86** [comment]
Thank you for your contribution @davidojedalopez 
Gracías por tu contribucion! :)

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-51d9afb6-b666-4b20-ac39-494c4b2f62a7-v1.png?transparent=1&palette=1&width=246)

**Comment by nitya** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository. 
We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 
This issue is now resolved! 🎉

**Comment by davidojedalopez** [comment]
Yeeei thanks a lot @nitya! 🥳

Is there a reason why my contributions to the other two challenges is not listed? They were added as PRs
