### ISSUE TITLE
Serveless Dreidel #day1

### ISSUE THREAD

**Issue by mofopeojosh** [microsoft/25-days-of-serverless#125]
Please provide the following information for your submission:

**Comment by nitya** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository. 
We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 
This issue is now resolved! 🎉
