### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/25-days-of-serverless#126]
Please provide the following information for your submission:

### What is your name? 
Ethan Arrowood

### Where is your GitHub Repo ?
https://github.com/Ethan-Arrowood/25-days-of-serverless-2019/tree/master/SecretSanta

### What Challenge is this for? (Challenge number between 1 and 25)
3

### (Optional) Anything else we should know? e.g., language used, location, blog post?
TypeScript, Azure Functions, Azure SQL

**Comment by nitya** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository. 
We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 
This issue is now resolved! 🎉
