### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by aguywithcode** [microsoft/25-days-of-serverless#128]
Please provide the following information for your submission:

### What is your name? (First, Last)
Michael Brown
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/aguywithcode/25-days-of-serverless/tree/solutions/week-1/challenge-2
### What Challenge is this for? (Challenge number between 1 and 25)
Challenge 2
### (Optional) Anything else we should know? e.g., language used, location, blog post?
Created a logic app that sends a reminder based on an http request with the following body format:

```
{
  "reminderDate": "2019-12-04T08:50:00Z",
  "phoneNumber": "+1 425 555 1212",
  "message": "light candles"
}
```

**Comment by nitya** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository. 
We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 
This issue is now resolved! 🎉
