### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/25-days-of-serverless#140]
Please provide the following information for your submission:

### What is your name? (First, Last)
Barbara Forbes
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/Ba4bes/25daysofserverless/tree/master/Day4potluck
### What Challenge is this for? (Challenge number between 1 and 25)
This is challenge 4 
( I had also entered challenge 2 in my first pull request; https://github.com/Ba4bes/25daysofserverless/tree/master/Day2Lucy )
### (Optional) Anything else we should know? e.g., language used, location, blog post?
This is PowerShell with a CosmosDB. It isn't the cleanest code, but I had no luck finding any documentation about connecting a PowerShell Function App to a cosmosDB (or any DB for that matter). So it took a lot of trial and error :-). Guess I need to blog about it myself soon😁

**Comment by glaucia86** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-51d9afb6-b666-4b20-ac39-494c4b2f62a7-v1.png?transparent=1&palette=1&width=246)
