### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge 4

### ISSUE THREAD

**Issue by marcduiker** [microsoft/25-days-of-serverless#144]
Please provide the following information for your submission:

### What is your name? (First, Last)
Marc Duiker

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/marcduiker/25daysofserverless2019/tree/master/src/Day04

### What Challenge is this for? (Challenge number between 1 and 25)
4

### (Optional) Anything else we should know? e.g., language used, location, blog post?
4 HttpTriggered functions backed by TableStorage.
https://twitter.com/marcduiker/status/1202356802140151815

**Comment by glaucia86** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-51d9afb6-b666-4b20-ac39-494c4b2f62a7-v1.png?transparent=1&palette=1&width=246)
