### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge 4

### ISSUE THREAD

**Issue by KevinJCandlert** [microsoft/25-days-of-serverless#146]
### What is your name? (First, Last)
Kevin, Candlert
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/KevinJCandlert/25-days-of-serverless-submissions/tree/master/25-days-of-serverless/day-4
### What Challenge is this for? (Challenge number between 1 and 25)
4
### (Optional) Anything else we should know? e.g., language used, location, blog post?
My day-4 project is currently deployed at https://day4-20191205122750.azurewebsites.net/api/food
I used C# with Table Storage as the built in binding was easy to use. I spent the majority of time investigating the Json.Net Schema library, it's really interesting and I didn't know it existed before.

**Comment by glaucia86** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-51d9afb6-b666-4b20-ac39-494c4b2f62a7-v1.png?transparent=1&palette=1&width=246)
