### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by wbprice** [microsoft/25-days-of-serverless#152]
Please provide the following information for your submission:

### What is your name? (First, Last)
Blaine Price

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/wbprice/25-days-of-serverless-2019-solutions/tree/master/4

### What Challenge is this for? (Challenge number between 1 and 25)
4

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Written in NodeJS, using Azure Functions and the Table API

**Comment by glaucia86** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉

**Comment by glaucia86** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉

![bitmoji](https://render.bitstrips.com/v2/cpanel/e19d1515-b426-4107-aad4-d62c37a20430-51d9afb6-b666-4b20-ac39-494c4b2f62a7-v1.png?transparent=1&palette=1&width=246)
