### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 5

### ISSUE THREAD

**Issue by GeradeDev** [microsoft/25-days-of-serverless#160]
### Where is your GitHub Repo
https://github.com/GeradeDev/25-days-of-serverless/tree/day04/week-1/Day5/NaughtyOrNice

### What Challenge is this for? (Challenge number between 1 and 25)
5

### (Optional) Anything else we should know? e.g., language used, location, blog post?
* Azure Function
* Language detector
* Text Translator
* Text analytics (Sentiment analysis)

**Comment by softchris** [comment]
looking good

**Comment by softchris** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
