### ISSUE TITLE
[CHALLENGE SUBMISSION] : Day5

### ISSUE THREAD

**Issue by rahulruikar** [microsoft/25-days-of-serverless#163]
Please provide the following information for your submission:

### What is your name? (First, Last)
Rahul Ruikar
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/rahulruikar/25DaysOfServerless/tree/master/Day5
### What Challenge is this for? (Challenge number between 1 and 25)
5
### (Optional) Anything else we should know? e.g., language used, location, blog post?
Azure Functions, Azure Cognitive Service

**Comment by softchris** [comment]
.net nice, reasonable solution

**Comment by softchris** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
