### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge 5

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/25-days-of-serverless#165]
Please provide the following information for your submission:

### What is your name? (First, Last)
Ethan Arrowood

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/Ethan-Arrowood/25-days-of-serverless-2019/tree/master/NaughtyOrNice

### What Challenge is this for? (Challenge number between 1 and 25)
Challenge 5

### (Optional) Anything else we should know? e.g., language used, location, blog post?
TypeScript, Azure Functions, Azure Cognitive Services Text Analysis

**Comment by softchris** [comment]
nice, points for explaining the process

**Comment by softchris** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
