### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge 5

### ISSUE THREAD

**Issue by FranzHelm** [microsoft/25-days-of-serverless#166]
Please provide the following information for your submission:

### What is your name? (First, Last)
Franz Helmberger

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/FranzHelm/hlc.25daysofserverless.chall5

### What Challenge is this for? (Challenge number between 1 and 25)
5

**Comment by softchris** [comment]
Thank you Franz. Nice solution

**Comment by softchris** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
