### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by wbprice** [microsoft/25-days-of-serverless#167]
Please provide the following information for your submission:

### What is your name? (First, Last)
Blaine Price

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/wbprice/25-days-of-serverless-2019-solutions/tree/master/5

### What Challenge is this for? (Challenge number between 1 and 25)
5

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Implemented in NodeJS, written using an Azure Function App and the Azure Text Analytics API

**Comment by softchris** [comment]
thank you

**Comment by softchris** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
