### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by scottrudy** [microsoft/25-days-of-serverless#196]
Please provide the following information for your submission:

### What is your name? 

Scott Rudy

### Where is your GitHub Repo ?(With your challenge solution)

https://github.com/scottrudy/25-days-of-serverless-dotnet/tree/master/day06

### What Challenge is this for? (Challenge number between 1 and 25)

6

### (Optional) Anything else we should know? e.g., language used, location, blog post?

C#, LUIS, DurableFunction

**Comment by jansche** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
