### ISSUE TITLE
[CHALLENGE SUBMISSION]  - Challenge 8

### ISSUE THREAD

**Issue by ChendrayanV** [microsoft/25-days-of-serverless#212]
### What is your name? (First, Last)
Chendrayan Venkatesan

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/ChendrayanV/iAzServerless
https://github.com/ChendrayanV/iAzServerless/tree/master/IncidentStatus

### What Challenge is this for? (Challenge number between 1 and 25)
8

### (Optional) Anything else we should know? e.g., language used, location, blog post?
PowerShell 😊 and Service Now REST API
The page auto refresh at required interval! 

```HTML - 2 min interval
meta -httpequiv "refresh" -content "120"
```
> Disabled for now by commenting - Cost Saving!

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @ChendrayanV for creating this issue!

Have a Happy Holiday season!

**Comment by jasonhand** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository and are thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 
This issue is now resolved! 🎉
