### ISSUE TITLE
[CHALLENGE SUBMISSION] Day 3

### ISSUE THREAD

**Issue by ckabates** [microsoft/25-days-of-serverless#213]
### What is your name? 

Colin Bates

### Where is your GitHub Repo ?

https://github.com/ckabates/25-days-of-serverless-solutions/tree/master/Day3

### What Challenge is this for?

3

### (Optional) Anything else we should know? 

C#, Azure Functions, CosmosDb

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @ckabates for creating this issue!

Have a Happy Holiday season!

**Comment by jansche** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
