### ISSUE TITLE
[CHALLENGE SUBMISSION] - Day 2

### ISSUE THREAD

**Issue by jolo-dev** [microsoft/25-days-of-serverless#219]
Please provide the following information for your submission:

### What is your name? (First, Last)
John Long
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/jolo-dev/azure-serverless/tree/jolo-challenge-1/challenge_2
### What Challenge is this for? (Challenge number between 1 and 25)
2
### (Optional) Anything else we should know? e.g., language used, location, blog post?
Typescript and Azure's Logic App (see Description of Repo)

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @jolo-dev for creating this issue!

Have a Happy Holiday season!

**Comment by jolo-dev** [comment]
I changed the Timezone to Swedish Time now.

**Comment by jansche** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
