### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 8

### ISSUE THREAD

**Issue by Bhawk90** [microsoft/25-days-of-serverless#220]
Please provide the following information for your submission:

### What is your name? (First, Last)
Gabor Gulyas

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/Bhawk90/25days-of-serverless/tree/master/day-8

### What Challenge is this for? (Challenge number between 1 and 25)
8

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Azure Functions, Azure Table Storage, SignalR and Blazor Web App. I've extended the application with not just showing a status, but a list of open incidents ;)

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @Bhawk90 for creating this issue!

Have a Happy Holiday season!

**Comment by jasonhand** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository and are thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 
This issue is now resolved! 🎉
