### ISSUE TITLE
[CHALLENGE SUBMISSION] Day 1

### ISSUE THREAD

**Issue by AryanJ-NYC** [microsoft/25-days-of-serverless#221]
### What is your name? (First, Last)
Aryan Jabbari
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/AryanJ-NYC/25-days-of-serverless-challenge-1
### What Challenge is this for? (Challenge number between 1 and 25)
1
### (Optional) Anything else we should know? e.g., language used, location, blog post?
Used TypeScript.

Streamed myself doing this challenge at:
https://www.twitch.tv/videos/519015745 (though I messed up and the audio isn't there, d'oh!)

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @AryanJ-NYC for creating this issue!

Have a Happy Holiday season!

**Comment by jansche** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION AND THE STREAM!!** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
