### ISSUE TITLE
[CHALLENGE SUBMISSION] - challange 10

### ISSUE THREAD

**Issue by PawelHaracz** [microsoft/25-days-of-serverless#269]
Please provide the following information for your submission:

### What is your name? (First, Last)
Pawel Haracz
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/PawelHaracz/25daysofserverless/tree/master/Day10
### What Challenge is this for? (Challenge number between 1 and 25)
10
### (Optional) Anything else we should know? e.g., language used, location, blog post?
Logic apps, blob storage, static webpage

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by paladique** [comment]
@PawelHaracz  👋 Thank you for your submission!! We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md#week-two---challenge-10)

Thank you for your contributions!
This issue is now resolved! 🎉
