### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by FranzHelm** [microsoft/25-days-of-serverless#272]
Please provide the following information for your submission:

### What is your name? (First, Last)
Franz Helmberger

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/FranzHelm/hlc.25daysofserverless.chall8

### What Challenge is this for? (Challenge number between 1 and 25)
8

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Angular - TypeScript - Azure Function - Azure SignalR Service - Blob Trigger

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by jasonhand** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository. 

We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 
This issue is now resolved! 🎉
