### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by scottrudy** [microsoft/25-days-of-serverless#274]
Please provide the following information for your submission:

### What is your name? (First, Last)

Rudy, Scott

### Where is your GitHub Repo ?(With your challenge solution)

https://github.com/scottrudy/25-days-of-serverless-dotnet/tree/master/day10

### What Challenge is this for? (Challenge number between 1 and 25)

10

### (Optional) Anything else we should know? e.g., language used, location, blog post?

Azure time triggered, C# function with API calls to Twitter API using Tweetinvi and input/output bindings for blob and table storage.

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by paladique** [comment]
@scottrudy  👋 Thank you for your submission!! We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md#week-two---challenge-10)

Thank you for your contributions!
This issue is now resolved! 🎉
