### ISSUE TITLE
[CHALLENGE SUBMISSION] 12

### ISSUE THREAD

**Issue by mochecki** [microsoft/25-days-of-serverless#289]
Please provide the following information for your submission:

### What is your name? (First, Last)
Mateusz Ochęcki
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/mochecki/25daysofserverless/tree/master/day12
### What Challenge is this for? (Challenge number between 1 and 25)
12
### (Optional) Anything else we should know? e.g., language used, location, blog post?
Azure Function 3.0, .net core 3.0, API Management (Consumption Plan) with caching policy.  
https://25daysofserverlessday12.z6.web.core.windows.net

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by jansche** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md) and you also earned the winner trophy there. Congrats!
Thank you for your contributions! 
This issue is now resolved! 🎉
