### ISSUE TITLE
[CHALLENGE SUBMISSION] - Day 1

### ISSUE THREAD

**Issue by abhishek0220** [microsoft/25-days-of-serverless#299]
Please provide the following information for your submission:

### What is your name? 
Abhishek Chaudhary

### Where is your GitHub Repo ?
https://github.com/abhishek0220/25daysofserverless/tree/master/challenge_1

### What Challenge is this for?
1

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Python

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by jansche** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
