### ISSUE TITLE
[CHALLENGE SUBMISSION] - Day 11

### ISSUE THREAD

**Issue by dpnl87** [microsoft/25-days-of-serverless#311]
Please provide the following information for your submission:

### What is your name? (First, Last)

Daniel Paulus

### Where is your GitHub Repo ?(With your challenge solution)

https://github.com/dpnl87/25daysofserverless2019/tree/master/src/day-11

### What Challenge is this for? (Challenge number between 1 and 25)

11

### (Optional) Anything else we should know? e.g., language used, location, blog post?

Used NodeJS and created 2 functions. A httpTrigger to create the entry in Cosmos with an JSON post and a cosomosTrigger to post the messages to Slack.

<img width="443" alt="Screenshot 2019-12-15 at 13 04 41" src="https://user-images.githubusercontent.com/85584/70862485-60757d00-1f3d-11ea-9fa3-9f5559e9f43a.png">

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by jansche** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
