### ISSUE TITLE
[CHALLENGE SUBMISSION] Day 15

### ISSUE THREAD

**Issue by dzsquared** [microsoft/25-days-of-serverless#321]
Please provide the following information for your submission:

### What is your name? (First, Last)
Drew Skwiers-Koballa
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/dzsquared/25-days-of-serverless-day15
### What Challenge is this for? (Challenge number between 1 and 25)
15
### (Optional) Anything else we should know? e.g., language used, location, blog post?
Typescript Azure Function with REST API call to Azure Computer Vision
Blog post: https://www.drewsk.tech/2019/12/15/25-days-of-serverless-day-15/

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by SandraAhlgrimm** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 

We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 

This issue is now resolved! 🎉
